In [66]:
import pandas as pd
import sklearn

In [67]:
df = pd.read_csv('dataset/spotify-tracks-dataset.csv')

In [68]:
df.iloc[0]

Unnamed: 0.1                             0
Unnamed: 0                               0
track_id            5SuOikwiRyPMVoIQDJUgSV
artists                        Gen Hoshino
album_name                          Comedy
track_name                          Comedy
popularity                              73
duration_ms                         230666
explicit                             False
danceability                         0.676
energy                               0.461
key                                      1
loudness                            -6.746
mode                                     0
speechiness                          0.143
acousticness                        0.0322
instrumentalness                  0.000001
liveness                             0.358
valence                              0.715
tempo                               87.917
time_signature                           4
track_genre                       acoustic
Name: 0, dtype: object

In [69]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'track_id', 'artists', 'album_name',
       'track_name', 'popularity', 'duration_ms', 'explicit', 'danceability',
       'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='str')

In [70]:
df['album_name'].unique()

<ArrowStringArray>
[                                                                                       'Comedy',
                                                                              'Ghost (Acoustic)',
                                                                                'To Begin Again',
                                        'Crazy Rich Asians (Original Motion Picture Soundtrack)',
                                                                                       'Hold On',
                                                                          'Days I Will Remember',
                                                                   'Is There Anybody Out There?',
                                                           'We Sing. We Dance. We Steal Things.',
                                                                                        'Hunger',
                                                                                       'Episode',
 ...
                                                    'Passion: Take It All (Live/Deluxe Edition)',
                                                                             'Ambient Attention',
                                                                                         'Ámbar',
                                                                  'Tibetanos Sonidos Relajantes',
                                                                           'The Rock Won't Move',
                                                                      'The Light Meets The Dark',
                                                                         'HUMAN (Deluxe) [Live]',
 '#20 Sueños Vividos - Música Intrumental Suave 2018 para Dormir Bien y Relajarse Profundamente',
                                                     'Frecuencias Álmicas en 432hz (Solo Piano)',
                                                                              'Revelation Songs']
Length: 46590, dtype: str

In [71]:
new_df = df[df['track_genre'] == 'indian']

In [72]:
new_df.head(3)

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
55000,55000,55000,0NLkVxf0PyxsXBG3EuZcJf,Anuv Jain,Gul,Gul,71,217241,False,0.600,...,-12.301,1,0.0292,0.871,0.000087,0.1020,0.342,86.970,4,indian
55001,55001,55001,6VBhH7CyP56BXjp8VsDFPZ,Pritam;Arijit Singh;Amitabh Bhattacharya,"Kesariya (From ""Brahmastra"")","Kesariya (From ""Brahmastra"")",88,268164,False,0.577,...,-6.525,1,0.0278,0.572,0.000000,0.1000,0.436,94.009,4,indian
55002,55002,55002,7MBqVOzb8C3f0FXr2LBLiq,OAFF;Savera;Lothika;Kausar Munir,"Doobey (From ""Gehraiyaan"")","Doobey (From ""Gehraiyaan"")",73,219686,False,0.751,...,-6.532,0,0.0359,0.342,0.000013,0.0822,0.359,119.014,4,indian

In [73]:
features = ['popularity', 'danceability', 'energy', 'loudness', 'acousticness', 'instrumentalness', 'liveness', 'valence' ]
info = ['track_id', 'artists', 'album_name', 'track_name']
new_df = new_df.drop_duplicates(subset='track_name').reset_index(drop=True)

In [74]:
# new_df = new_df[info +  features]
new_df = new_df[info + features]

In [75]:
new_df

,track_id,artists,album_name,track_name,popularity,danceability,energy,loudness,acousticness,instrumentalness,liveness,valence
0,0NLkVxf0PyxsXBG3EuZcJf,Anuv Jain,Gul,Gul,71,0.600,0.294,-12.301,0.871,0.000087,0.1020,0.342
1,6VBhH7CyP56BXjp8VsDFPZ,Pritam;Arijit Singh;Amitabh Bhattacharya,"Kesariya (From ""Brahmastra"")","Kesariya (From ""Brahmastra"")",88,0.577,0.574,-6.525,0.572,0.000000,0.1000,0.436
2,7MBqVOzb8C3f0FXr2LBLiq,OAFF;Savera;Lothika;Kausar Munir,"Doobey (From ""Gehraiyaan"")","Doobey (From ""Gehraiyaan"")",73,0.751,0.669,-6.532,0.342,0.000013,0.0822,0.359
3,1rDjwexewf4hrdZT7SRNsH,Faridkot;Amar Jalal,Nasha (Equals Sessions) - Single,Nasha (Equals Sessions),70,0.780,0.460,-7.516,0.455,0.000141,0.0610,0.788
4,7cWnks0lsRtpAi87COOiXK,Salim–Sulaiman;Rahat Fateh Ali Khan;Jaideep Sahni,Aaja Nachle,O Re Piya,71,0.586,0.532,-8.837,0.779,0.000565,0.1240,0.494
...,...,...,...,...,...,...,...,...,...,...,...,...
958,00bOo6r6YhVnxzDu4JhCWX,Papon,Bajrangi Bhaijaan,Tu Jo Mila (Reprise),42,0.473,0.441,-9.205,0.850,0.000159,0.1160,0.265
959,1TxtDLNSEJANynR9Xp5TMe,Aamir Khan,Chan Mahiya,Chan Mahiya,40,0.522,0.661,-3.098,0.466,0.000000,0.0802,0.329
960,2iLeerAUsEou9jRdBYZsVU,Pritam;Sarwar Khan;Sartaz Khan Barna,Dangal (Original Motion Picture Soundtrack),Haanikaarak Bapu,42,0.629,0.837,-6.179,0.150,0.000479,0.0578,0.803
961,17CHY0FoOgypamXGpk0Kqj,Ajay Singha;Nirmalya Humtoo Dey,"Bollywood Love Instrumentals, Vol. 2",Tu Tu Hai Wohi - Unwind Instrumental,43,0.690,0.335,-15.583,0.782,0.902000,0.0926,0.390
962,2w4wjkhy7jwhxpM90xKjHK,Jitendra Thankur;Shomu Seal,Relax with Bollywood Instrumentals,Chhukar Mere Man Ko - Unwind Instrumental,43,0.711,0.353,-12.572,0.861,0.863000,0.1040,0.357

In [76]:
new_df.isnull().sum()

track_id            0
artists             0
album_name          0
track_name          0
popularity          0
danceability        0
energy              0
loudness            0
acousticness        0
instrumentalness    0
liveness            0
valence             0
dtype: int64

In [77]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
scalar = StandardScaler()
x = new_df[features]
X_scaled = scalar.fit_transform(x)
similarity = cosine_similarity(X_scaled)

In [78]:
new_df.iloc[0]

track_id            0NLkVxf0PyxsXBG3EuZcJf
artists                          Anuv Jain
album_name                             Gul
track_name                             Gul
popularity                              71
danceability                           0.6
energy                               0.294
loudness                           -12.301
acousticness                         0.871
instrumentalness                  0.000087
liveness                             0.102
valence                              0.342
Name: 0, dtype: object

In [79]:
import re

def clean_name(name):
    name = re.sub(r'\(.*?\)', '', name)   # (From "Brahmastra") jaisa bracket wala hissa hatao
    name = re.sub(r'\s-\s.*$', '', name)  # " - Lofi Flip" jaisa dash ke baad wala hissa hatao
    return name.strip().lower()

In [80]:
def recommend(song_name):
    song_index = new_df.index[new_df['track_name'] == song_name].tolist()
    if song_index == []:
        return 'Song Not Available'

    scores = similarity[song_index[0]]
    sorted_value = sorted(enumerate(scores), key=lambda x : x[1], reverse=True)
    seen = {clean_name(song_name)}
    recommended_songs= []
    for idx, score in sorted_value:
       base = clean_name(new_df.iloc[idx]['track_name'])
       if base in seen:
           continue
       seen.add(base)
       recommended_songs.append(new_df.iloc[idx][['track_name', 'artists']].to_dict())
       if len(recommended_songs) == 5:
           break
    return recommended_songs

In [81]:
similarity.shape

(963, 963)

In [82]:
recommend('Kesariya')

[{'track_name': 'Kalank (Title Track)', 'artists': 'Pritam;Arijit Singh'},
 {'track_name': 'Theethiriyaai (From "Brahmastra (Tamil)")',
  'artists': 'Pritam;Sid Sriram'},
 {'track_name': 'Deva Deva (From "Brahmastra")',
  'artists': 'Pritam;Arijit Singh;Amitabh Bhattacharya;Jonita Gandhi'},
 {'track_name': 'Ranjha (From "Shershaah")',
  'artists': 'Jasleen Royal;B Praak;Romy;Anvita Dutt'},
 {'track_name': 'Hawayein', 'artists': 'Pritam;Arijit Singh'}]

In [83]:
recommend('Gul')

[{'track_name': 'Tuta Pull Wahan', 'artists': 'Deepak Rathore Project'},
 {'track_name': 'Alag Aasmaan', 'artists': 'Anuv Jain'},
 {'track_name': 'Din Shagna Da', 'artists': 'Jasleen Royal'},
 {'track_name': 'Ranjha - Lofi Flip',
  'artists': 'VIBIE;Jasleen Royal;B Praak'},
 {'track_name': 'Waqt Ki Baatein', 'artists': 'Dream Note'}]

In [84]:
recommend('124rmmklq')

'Song Not Available'

In [88]:
import pickle
with open('songs.pkl', 'wb') as f:
    pickle.dump(new_df, f)
with open('similarity.pkl', 'wb') as f:
    pickle.dump(similarity, f)

In [91]:
import requests
response = requests.get(f'https://itunes.apple.com/search?term={'Keshariya'}&entity=song&limit=1')
print(response.json())

{'resultCount': 1, 'results': [{'wrapperType': 'track', 'kind': 'song', 'artistId': 213157068, 'collectionId': 1635013814, 'trackId': 1635014240, 'artistName': 'Pritam, Arijit Singh & Amitabh Bhattacharya', 'collectionName': 'Kesariya (From "Brahmastra") - Single', 'trackName': 'Kesariya (From "Brahmastra")', 'collectionCensoredName': 'Kesariya (From "Brahmastra") - Single', 'trackCensoredName': 'Kesariya (From "Brahmastra")', 'artistViewUrl': 'https://music.apple.com/us/artist/pritam/213157068?uo=4', 'collectionViewUrl': 'https://music.apple.com/us/album/kesariya-from-brahmastra/1635013814?i=1635014240&uo=4', 'trackViewUrl': 'https://music.apple.com/us/album/kesariya-from-brahmastra/1635013814?i=1635014240&uo=4', 'previewUrl': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/38/4c/5c/384c5c8f-3ff8-e457-b2f7-3158ce108649/mzaf_12389299033886433185.plus.aac.p.m4a', 'artworkUrl30': 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/9f/13/ca/9f13ca3b-e533-03e0-f19a-f0aaa774581d/196589311191.jpg/30x30bb.jpg', 'artworkUrl60': 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/9f/13/ca/9f13ca3b-e533-03e0-f19a-f0aaa774581d/196589311191.jpg/60x60bb.jpg', 'artworkUrl100': 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/9f/13/ca/9f13ca3b-e533-03e0-f19a-f0aaa774581d/196589311191.jpg/100x100bb.jpg', 'collectionPrice': 1.29, 'trackPrice': 1.29, 'releaseDate': '2022-07-17T12:00:00Z', 'collectionExplicitness': 'notExplicit', 'trackExplicitness': 'notExplicit', 'discCount': 1, 'discNumber': 1, 'trackCount': 1, 'trackNumber': 1, 'trackTimeMillis': 268165, 'country': 'USA', 'currency': 'USD', 'primaryGenreName': 'Bollywood', 'isStreamable': True}]}

In [92]:
import requests

response = requests.get(
    'https://itunes.apple.com/search',
    params={'term': 'Kesariya', 'entity': 'song', 'limit': 1}
)

data = response.json()
print(data)
print(data['results'][0]['previewUrl'])

{'resultCount': 1, 'results': [{'wrapperType': 'track', 'kind': 'song', 'artistId': 213157068, 'collectionId': 1635013814, 'trackId': 1635014240, 'artistName': 'Pritam, Arijit Singh & Amitabh Bhattacharya', 'collectionName': 'Kesariya (From "Brahmastra") - Single', 'trackName': 'Kesariya (From "Brahmastra")', 'collectionCensoredName': 'Kesariya (From "Brahmastra") - Single', 'trackCensoredName': 'Kesariya (From "Brahmastra")', 'artistViewUrl': 'https://music.apple.com/us/artist/pritam/213157068?uo=4', 'collectionViewUrl': 'https://music.apple.com/us/album/kesariya-from-brahmastra/1635013814?i=1635014240&uo=4', 'trackViewUrl': 'https://music.apple.com/us/album/kesariya-from-brahmastra/1635013814?i=1635014240&uo=4', 'previewUrl': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/38/4c/5c/384c5c8f-3ff8-e457-b2f7-3158ce108649/mzaf_12389299033886433185.plus.aac.p.m4a', 'artworkUrl30': 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/9f/13/ca/9f13ca3b-e533-03e0-f19a-f0aaa774581d/196589311191.jpg/30x30bb.jpg', 'artworkUrl60': 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/9f/13/ca/9f13ca3b-e533-03e0-f19a-f0aaa774581d/196589311191.jpg/60x60bb.jpg', 'artworkUrl100': 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/9f/13/ca/9f13ca3b-e533-03e0-f19a-f0aaa774581d/196589311191.jpg/100x100bb.jpg', 'collectionPrice': 1.29, 'trackPrice': 1.29, 'releaseDate': '2022-07-17T12:00:00Z', 'collectionExplicitness': 'notExplicit', 'trackExplicitness': 'notExplicit', 'discCount': 1, 'discNumber': 1, 'trackCount': 1, 'trackNumber': 1, 'trackTimeMillis': 268165, 'country': 'USA', 'currency': 'USD', 'primaryGenreName': 'Bollywood', 'isStreamable': True}]}
https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/38/4c/5c/384c5c8f-3ff8-e457-b2f7-3158ce108649/mzaf_12389299033886433185.plus.aac.p.m4a